//
// Created by kosenko on 9/8/24.
//

#ifndef BFO_CLI_READING_LIST_SRC_TERMINAL_UI_MENUS_TABLE_SELECTION_MENU_H
#define BFO_CLI_READING_LIST_SRC_TERMINAL_UI_MENUS_TABLE_SELECTION_MENU_H

#endif //BFO_CLI_READING_LIST_SRC_TERMINAL_UI_MENUS_TABLE_SELECTION_MENU_H
